---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.5
  kernelspec:
    display_name: single_cell_integration
    language: python
    name: single_cell_integration
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: .py
    mimetype: text/x-python
    name: python
    nbconvert_exporter: python
    pygments_lexer: ipython3
    version: 3.6.6
---

```{python}
# %load_ext autoreload
# %autoreload 2
import pandas as pd
import scanpy.api as sc
import numpy as np
import sys
sys.path.append("lib")
from jupytertools import setwd
from scio import concatenate
import os.path
import gc
setwd()
```

In the single cell tutorial at ECCB 2018, RuvSeq was used to remove "unwanted variation"
https://ppapasaikas.github.io/ECCB2018_SC/#ruvseq. 

RUVSeq takes per-cell-normalized, non-log-transformed counts as input. 

```{r}
library(RUVSeq)
library(reticulate)
```

```{python}
INPUT_FILE = r.params['input_file']
OUT_FILE = r.params['output_file'] 
```

```{python}
adata = sc.read(INPUT_FILE)
```

```{python}
# Load housekeeping genes
hk_genes = pd.read_csv("tables/housekeeping_genes.txt", comment="#", sep="\t")
hk_genes.columns = ["gene_symbol", "NM"]
biomart = pd.read_csv("tables/biomart.tsv", sep="\t")

# map them to ENSG
ensg_hk = np.unique(
    biomart.join(hk_genes.set_index("gene_symbol"), on="HGNC symbol", how="inner")["Gene stable ID"].values)
```

```{python}
ensg_hk_fil = adata.var_names[adata.var_names.isin(ensg_hk)]
sc.pp.filter_genes(adata, min_cells=1)
sc.pp.normalize_per_cell(adata, counts_per_cell_after=3000)
counts_mat = adata.X.T.toarray()
adata.X = None
gc.collect()
```

```{r transfer-data}
counts_mat = py$counts_mat
```

```{python cleanup}
del counts_mat
gc.collect()
```

```{r}
# k = number of factors of unwanted variation. 
# there are at least 2 (dataset + patient)
# could also try more...
counts_ruvg = RUVg(counts_mat, py$ensg_hk_fil, k=2)
```