SRA_ACCESSIONS = [l.split()[0].strip() for l in open("SRR_Acc_List.txt").readlines()]
OUT_DIR = "/naslx/projects/pn69di/ga75tit2/single_cell_integration/raw/azizi_peer_2018/fastq"

rule fastq:
  """run download"""
  input:
    expand(OUT_DIR + "/{accession}_pass_1.fastq.gz", accession=SRA_ACCESSIONS),
    expand(OUT_DIR + "/{accession}_pass_2.fastq.gz", accession=SRA_ACCESSIONS)


rule download_fastq:
  """download fastq"""
  output:
    OUT_DIR + "/{accession}_pass_1.fastq.gz",
    OUT_DIR + "/{accession}_pass_2.fastq.gz"
  params:
    accession="{accession}"
  conda:
    "envs/fastq.yml"
  shell:
    "fastq-dump --outdir " + OUT_DIR + " "
    "--gzip --skip-technical --readids "
    "--read-filter pass --dumpbase --split-files --clip {params.accession}"
