channels:
  - conda-forge
  - bioconda
  - defaults
  - grst
dependencies:
  - python=3.6.6
  - numpy=1.15.3
  - numpy-base=1.15.3
  - pandas=0.23.4
  - papermill=0.14.2
  - jupytext=0.8.6
  - ipykernel=5.1.0
