```{r setup}
library(conflicted)
library(readr)
library(dplyr)
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
library(stringr)
library(tidyr)
library(tibble)
library(magrittr)
library(testit)
library(AnnotationDbi)
library(org.Hs.eg.db)
```

# Get all data into a format that can be processed by scanorama, seurat or scanpy. 
That is, 
 * either a genes x cell matrix
 * a 10x sparse matrix. 



```{r}
azizi_peer = new.env()
with(azizi_peer, {
  raw_counts = read_csv("../data/azizi_peer_2018/GSE114725_raw_counts.csv")
  meta = raw_counts %>% select(patient, tissue, replicate, cluster, cellid)
  mat = raw_counts %>% mutate(cell_name = str_c(patient, tissue, cellid, sep="_")) %>% 
    select(-patient, -replicate, -cluster, -cellid, -tissue) %>%
    as.data.frame() %>% 
    column_to_rownames("cell_name") %>%
    t() %>% 
    as_tibble(rownames="gene")
  system("mkdir -p ../results/data_processed/azizi_peer_2018")
  write_tsv(mat,  "../results/data_processed/azizi_peer_2018/raw_counts.txt")
  write_tsv(meta, "../results/data_processed/azizi_peer_2018/pdata.tsv")
})

rm(azizi_peer)
```

```{r}
azizi_peer_10x = new.env()
with(azizi_peer_10x, {
   raw_counts = read_tsv("../data/azizi_peer_2018_10x/GSE114724_raw_counts.txt") 
   cell_barcode = raw_counts[1,-1] %>% as.character()
   sample_names = colnames(raw_counts)[-1]
   assert(length(cell_barcode) == length(sample_names))
   cell_names = str_c(sample_names, cell_barcode, sep="_")
   colnames(raw_counts) = c("gene", cell_names)
   system("mkdir -p ../results/data_processed/azizi_peer_2018_10x")
   raw_counts %>% filter(gene != "Sample_Barcodes") %>% 
     write_tsv("../results/data_processed/azizi_peer_2018_10x/raw_counts.txt")

})

rm(azizi_peer_10x)

```


```{r guo-zhang}
guo_zhang_2018 = new.env()
with(guo_zhang_2018, {
  patient_data = read_tsv("../data/guo_zhang_2018/patient_table.tsv")
  raw_counts = read_tsv("../data/guo_zhang_2018/GSE99254_NSCLC.TCell.S12346.count.txt.gz")
  system("mkdir -p ../results/data_processed/guo_zhang_2018")
  write_tsv(patient_data, "../results/data_processed/guo_zhang_2018/pdata.tsv")
  raw_counts %>% select(-geneID) %>% drop_na() %>% write_tsv("../results/data_processed/guo_zhang_2018/raw_counts.txt")
})
rm(guo_zhang_2018)
```

```{r savas-loi}
system(paste("mkdir -p", "../results/data_processed/savas_loi_2018"))
system(paste("cp", "../data/savas_loi_2018/GSE110686_tils20+32_barcodes.tsv", "../results/data_processed/savas_loi_2018/barcodes.tsv"))
system(paste("cp", "../data/savas_loi_2018/GSE110686_tils20+32_genes.tsv", "../results/data_processed/savas_loi_2018/genes.tsv"))
system(paste("cp", "../data/savas_loi_2018/GSE110686_tils20+32_matrix.mtx", "../results/data_processed/savas_loi_2018/matrix.mtx"))
```


```{r zheng-bileas}
system(paste("mkdir -p", "../results/data_processed/zheng_bileas_2017"))
system(paste("cp", "../data/zheng_bileas_2017/barcodes.tsv", "../results/data_processed/zheng_bileas_2017/barcodes.tsv"))
system(paste("cp", "../data/zheng_bileas_2017/genes.tsv", "../results/data_processed/zheng_bileas_2017/genes.tsv"))
system(paste("cp", "../data/zheng_bileas_2017/matrix.mtx", "../results/data_processed/zheng_bileas_2017/matrix.mtx"))
```

```{r zheng-zhang}
zheng_zhang = new.env()
with(zheng_zhang, {
  patient_data = read_tsv("../data/zheng_zhang_2017/patient_table.tsv")
  raw_counts = read_tsv("../data/zheng_zhang_2017/GSE98638_HCC.TCell.S5063.count.txt.gz")
  system("mkdir -p ../results/data_processed/zheng_zhang_2017")
  write_tsv(patient_data, "../results/data_processed/zheng_zhang_2017/pdata.tsv")
  raw_counts %>% select(-geneID) %>% drop_na() %>% write_tsv("../results/data_processed/zheng_zhang_2017/raw_counts.txt")
})
rm(zheng_zhang)
```

```{bash}
find ../results/data_processed | grep mtx$ | xargs readlink -f | xargs dirname > ../results/data_processed/datasets.txt
find ../results/data_processed | grep raw_counts | xargs readlink -f >> ../results/data_processed/datasets.txt
```

