LOCAL:
    temp-directory: /storage/scratch
    memory: 4g
META:
    species:
        - HUMAN
    ratio: 0
    reference-file: human_grch38.fasta
    annotation-file: Homo_sapiens.GRCh38.83.gtf
    reference-directory: /storage/data/reference/homo_sapiens/GRCh38/dropSeqPipe
FILTER:
    5-prime-smart-adapter: CCTACACGACGCTCTTCCGATCT
    cell-barcode:
        start: 1
        end: 16
    UMI-barcode:
        start: 17
        end: 26
    cutadapt:
        adapters-file: adapters_10x_3p_v2.fa
        R1:
            quality-filter: 20
            maximum-Ns: 0
            extra-params: ''
        R2:
            quality-filter: 20
            minimum-adapters-overlap: 6
            minimum-length: 15
            extra-params: ''
EXTRACTION:
    UMI-edit-distance: 2
    minimum-counts-per-UMI: 1
MAPPING:
    STAR:
        genomeChrBinNbits: 18
        outFilterMismatchNmax: 10
        outFilterMismatchNoverLmax: 0.3
        outFilterMismatchNoverReadLmax: 1
        outFilterMatchNmin: 0
        outFilterMatchNminOverLread: 0.66
        outFilterScoreMinOverLread: 0.66
