LOCAL:
    temp-directory: /gpfs/scratch/pn69di/ga75tit
    memory: 4g
META:
    species:
        - HUMAN
    reference-directory: /naslx/projects/pn69di/ga75tit/reference
FILTER:
    5-prime-smart-adapter: CCTACACGACGCTCTTCCGATCT
    cell-barcode:
        start: 1
        end: 12
    UMI-barcode:
        start: 13
        end: 26
    cutadapt:
        adapters-file: Chromium.fa
        R1:
            quality-filter: 20
            maximum-Ns: 0
            extra-params: ''
        R2:
            quality-filter: 20
            minimum-adapters-overlap: 6
            minimum-length: 15
            extra-params: ''
EXTRACTION:
    UMI-edit-distance: 2
    minimum-counts-per-UMI: 1
MAPPING:
    STAR:
        genomeChrBinNbits: 18
        outFilterMismatchNmax: 10
        outFilterMismatchNoverLmax: 0.3
        outFilterMismatchNoverReadLmax: 1
        outFilterMatchNmin: 0
        outFilterMatchNminOverLread: 0.66
        outFilterScoreMinOverLread: 0.66
