---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.5
  kernelspec:
    display_name: single_cell_integration
    language: python
    name: single_cell_integration
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: .py
    mimetype: text/x-python
    name: python
    nbconvert_exporter: python
    pygments_lexer: ipython3
    version: 3.6.6
---

```{python}
# %load_ext autoreload
# %autoreload 2
import pandas as pd
import scanpy.api as sc
import numpy as np
import sys
sys.path.append("lib")
from jupytertools import setwd
from scio import concatenate
import os.path
import gc
import rpy2
import rpy2.robjects.numpy2ri
rpy2.robjects.numpy2ri.activate()
setwd()
```

```{python}
# %load_ext rpy2.ipython
```

```{r}
library(harmony)
library(magrittr)
```

```{python}
INPUT_FILE = r.params['input_file']
OUT_FILE = r.params['output_file'] 
```

```{python}
adata = sc.read(INPUT_FILE)
```

```{python}
sc.tl.pca(adata, svd_solver='arpack')
```

```{python}
batch_vector = adata.obs["dataset"].values.tolist()
pca_mat = np.matrix(adata.obsm["X_pca"])
```

```{r magic_args='-i pca_mat -i batch_vector -o harmony_embeddings'}
harmony_embeddings <- HarmonyMatrix(pca_mat, batch_vector)
```

```{python}
#sdata = seurat data
# %%R
sdata = Convert(py$adata, to = "seurat")
```

```{r}
sdata %<>% RunPCA(pcs.compute = 20)
```

```{python}
# run harmony
options(repr.plot.height = 3, repr.plot.width = 6)
system.time(pbmc %<>% RunHarmony("stim", theta = 2, plot_convergence = TRUE, nclust = 50, max.iter.cluster = 100))
```

```{r}
# convert back to python
adata2 = Convert(from = sdata, to = "anndata")
```

```{python}
sc.pp.neighbors(adata_corrected, n_neighbors=10, n_pcs=40)
sc.tl.umap(adata_corrected)
```
